version: '3.0'
services:
  webapi:
    # https://github.com/maziarz/apistar-docker
    build: 
      context: .
      dockerfile: ./Dockerfile.api
    command: gunicorn dockerentry:app --workers=4 --bind=0.0.0.0:5000 --pid=pid --worker-class=meinheld.gmeinheld.MeinheldWorker
    volumes:
      - ./webapi:/src/webapi:ro
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - testnetwork
    logging:
      options:
        max-size: "1m"
        max-file: "1"

  swagger:
    image: swaggerapi/swagger-ui
    environment:
      - API_URL=/schema/
    ports:
      - "4000:8080"
    networks:
      - testnetwork
    logging:
      options:
        max-size: "1m"
        max-file: "1"

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d:ro
    ports:
      - "8081:80"
    networks:
      - testnetwork
    logging:
      options:
        max-size: "1m"
        max-file: "1"

networks:
    testnetwork:
        driver: bridge
